# Generated by Django 5.2.10 on 2026-01-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250, unique=True, verbose_name='Question')),
                ('option_a', models.CharField(max_length=150, verbose_name='Option A')),
                ('option_b', models.CharField(max_length=150, verbose_name='Option B')),
                ('option_c', models.CharField(max_length=150, verbose_name='Option C')),
                ('option_d', models.CharField(max_length=150, verbose_name='Option D')),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Correct answer')),
            ],
        ),
    ]
